<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;Debug R2025;Debug R2026;Release R2025;Release R2026</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RevitActionRecorder.Model\RevitActionRecorder.Model.csproj" />
  </ItemGroup>

</Project>
